---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lzh.
--- DateTime: 2024-11-12 19:48
---
print("启动CtrlMgr.lua")

require("Download/xLuaLogic/Common/Define")
require("Download/xLuaLogic/Modules/Raffle/RaffleCtrl")

CtrlMgr = {}

local this=CtrlMgr
-- 控制器列表
local ctrlList = {}
-- 初始化 往列表中添加所有的控制器
function CtrlMgr.Init()
    ctrlList[CtrlName.RaffleCtrl]=RaffleCtrl.New()
    return this
end

-- 根据控制器的名称获取控制器
function CtrlMgr.GetCtrl(ctrlName)
    return ctrlList[ctrlName]
end

-- 销毁 销毁所有的控制器
function CtrlMgr.OnDestroy()
    for k,v in pairs(ctrlList) do
        v:OnDestroy()
    end
end
