---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lzh.
--- DateTime: 2024-11-12 19:48
---
print("启动GameInit.lua")
-- 加载全局配置
--require可以引入外部的脚本或模块，并在当前脚本中使用这些模块的功能或变量。
require("Download/xLuaLogic/CtrMgr")
require("Download/xLuaLogic/Common/Define")
GameInit = {}
local this = GameInit

function GameInit.InitView()
        require(string.format("Download/xLuaLogic/Modules/Raffle/RaffleView"));
end
--只初始化，不加载界面
function GameInit.Init()
    this.InitView()
    CtrlMgr.Init()
   -- DBModelMgr.Init()
    this.InitLoadView()

end
--通过C#调用加载界面type加载界面
function GameInit.LoadView(type)
    print("加载界面"..type)
    CtrlMgr.OnDestroy()
    local ctrl=CtrlMgr.GetCtrl(type)
    if  ctrl ~=nil then
        ctrl.Awake()
    end
end


function GameInit.InitLoadView()
    luaMgr:InitLoadView(this.LoadView)

end


return GameInit