---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lzh.
--- DateTime: 2024-11-19 10:30
---
RaffleView = {}

local this=RaffleView
local transform
local gameObject
--local RaffleTipInfoTrans
function RaffleView.Awake(go)
    print("RaffleView Awake")
    gameObject = go
    transform = go.transform
    this.RaffleTipInfoTrans =LuaHelper.MainCitySys.shopWnd.RaffleTipInfo.transform

    this.InitView()
end

function RaffleView.InitView()
    --TODO:初始化View
    this.gameBehaviour = gameObject:GetComponent("LuaViewBehaviour")
    this.ItemContent=transform:Find("RaffleContent")
    this.SingledrawBtn=transform:Find("RaffleBtns/Singledraw"):GetComponent("UnityEngine.UI.Button")
    this.TandrawBtn=transform:Find("RaffleBtns/Tandraw"):GetComponent("UnityEngine.UI.Button")
    this.btn_Close=this.RaffleTipInfoTrans:Find("TipInfo/btn_Close"):GetComponent("UnityEngine.UI.Button")
    this.RaffleTipInfoContent=this.RaffleTipInfoTrans:Find("TipInfo/ShopSlots/Scroll View/Viewport/Content")
    this.SureBtn=this.RaffleTipInfoTrans:Find("TipInfo/SureImg/SureBtn"):GetComponent("UnityEngine.UI.Button")
end
function RaffleView.enable()

end
function RaffleView.start()
    --TODO:启动View

end

function RaffleView.update()
    --TODO:更新View
end
function RaffleView.disable()
    --TODO:禁用View
end

function RaffleView.onDestroy()
    --TODO:销毁View
end