---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lzh.
--- DateTime: 2024-11-13 19:06
---

CtrlTemplate = {}

local this=UIRootCtrl
local transform;
local gameObject;

function UIRootCtrl.New()
    return this
end
function UIRootCtrl.Awake()

end
function UIRootCtrl.OnCreate(obj)

end