---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lzh.
--- DateTime: 2024-11-13 19:07
---
ViewTemplate = {}

local this=ViewTemplate
local transform
local gameObject

function TaskView.Awake(go)
    gameObject = go
    transform = go.transform
    this.InitView()
end

function ViewTemplate.InitView()
    --TODO:初始化View

end

function ViewTemplate.start()
    --TODO:启动View
end

function ViewTemplate.update()
    --TODO:更新View
end

function ViewTemplate.onDestroy()
    --TODO:销毁View
end