---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lzh.
--- DateTime: 2024-11-19 10:30
---
RaffleView = {}

local this=RaffleView
local transform
local gameObject

function RaffleView.Awake(go)
    gameObject = go
    transform = go.transform
    this.InitView()
end

function RaffleView.InitView()
    --TODO:初始化View
    gameObject:SetActive(true)
    this.ItemContent=transform:Find("RaffleContent")
end

function RaffleView.start()
    --TODO:启动View
end

function RaffleView.update()
    --TODO:更新View
end

function RaffleView.onDestroy()
    --TODO:销毁View
end